import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import s3 from './init'
import { PutObjectRequest } from 'aws-sdk/clients/s3'
import axios from 'axios'

type Props = {
  images: string[]
}

const Home: NextPage<Props> = ({ images }) => {
  const [inputFile, setInputFile] = useState<any>();
  const [progress, setProgress] = useState<number>();

  useEffect(() => {
    if (inputFile){
      let params: PutObjectRequest = {
        Body: inputFile,
        Bucket: process.env.BUCKET_NAME || "",
        Key: 'images/' + inputFile.name,
        ACL: 'public-read'
      }

      s3.putObject(params, function(err){
        if (err){
          console.log(err)
        } else {
          console.log("Success!")
        }
      }).on('httpUploadProgress', (evt) => {
        setProgress(Math.round((evt.loaded / evt.total) * 100))
      })
    }
    
  }, [inputFile])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
        <h1>Upload File</h1>
        <input type="file" accept="image/*" onChange={(e) => setInputFile(e.target.files && e.target.files[0])}/>
        {progress !== 100 && progress && <h2>Progress: {progress}%</h2>}
        {images.map((image: string) => (
          <h3 key={image}>{image}</h3>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


export const getStaticProps: GetStaticProps<Props> = async () => {
  const res = await axios.get('http://localhost:3000/api/list')
  const images: string[] = res.data

  return {
    props: {
      images
    }
  }
  
}

export default Home
